language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script: 
  - RAILS_ENV=test bundle exec rake db:structure:load --trace
  - bundle exec rake
before_script:
  - psql -c 'create database myapp_test' -U postgres
bundler_args: --binstubs=./bundler_stubs

branches:
  only:
    - master
